/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AproposRouteImport } from './routes/apropos'
import { Route as LeconsIndexRouteImport } from './routes/lecons.index'
import { Route as LeconsLessonIdRouteImport } from './routes/lecons.$lessonId'
import { Route as MaterielIndexRouteImport } from './routes/materiel.index'
import { Route as MaterielMaterielIdRouteImport } from './routes/materiel.$materielId'
import { Route as MaterielJeuRouteImport } from './routes/materiel.jeu'
import { Route as QcmIndexRouteImport } from './routes/qcm.index'
import { Route as QcmQuizIdRouteImport } from './routes/qcm.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AproposRoute = AproposRouteImport.update({
  id: '/apropos',
  path: '/apropos',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsIndexRoute = LeconsIndexRouteImport.update({
  id: '/lecons/',
  path: '/lecons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsLessonIdRoute = LeconsLessonIdRouteImport.update({
  id: '/lecons/$lessonId',
  path: '/lecons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterielIndexRoute = MaterielIndexRouteImport.update({
  id: '/materiel/',
  path: '/materiel/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterielMaterielIdRoute = MaterielMaterielIdRouteImport.update({
  id: '/materiel/$materielId',
  path: '/materiel/$materielId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterielJeuRoute = MaterielJeuRouteImport.update({
  id: '/materiel/jeu',
  path: '/materiel/jeu',
  getParentRoute: () => rootRouteImport,
} as any)
const QcmIndexRoute = QcmIndexRouteImport.update({
  id: '/qcm/',
  path: '/qcm/',
  getParentRoute: () => rootRouteImport,
} as any)
const QcmQuizIdRoute = QcmQuizIdRouteImport.update({
  id: '/qcm/$quizId',
  path: '/qcm/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apropos': typeof AproposRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/materiel/$materielId': typeof MaterielMaterielIdRoute
  '/materiel/jeu': typeof MaterielJeuRoute
  '/qcm/$quizId': typeof QcmQuizIdRoute
  '/lecons/': typeof LeconsIndexRoute
  '/materiel/': typeof MaterielIndexRoute
  '/qcm/': typeof QcmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apropos': typeof AproposRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/materiel/$materielId': typeof MaterielMaterielIdRoute
  '/materiel/jeu': typeof MaterielJeuRoute
  '/qcm/$quizId': typeof QcmQuizIdRoute
  '/lecons': typeof LeconsIndexRoute
  '/materiel': typeof MaterielIndexRoute
  '/qcm': typeof QcmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apropos': typeof AproposRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/materiel/$materielId': typeof MaterielMaterielIdRoute
  '/materiel/jeu': typeof MaterielJeuRoute
  '/qcm/$quizId': typeof QcmQuizIdRoute
  '/lecons/': typeof LeconsIndexRoute
  '/materiel/': typeof MaterielIndexRoute
  '/qcm/': typeof QcmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apropos'
    | '/lecons/$lessonId'
    | '/materiel/$materielId'
    | '/materiel/jeu'
    | '/qcm/$quizId'
    | '/lecons/'
    | '/materiel/'
    | '/qcm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apropos'
    | '/lecons/$lessonId'
    | '/materiel/$materielId'
    | '/materiel/jeu'
    | '/qcm/$quizId'
    | '/lecons'
    | '/materiel'
    | '/qcm'
  id:
    | '__root__'
    | '/'
    | '/apropos'
    | '/lecons/$lessonId'
    | '/materiel/$materielId'
    | '/materiel/jeu'
    | '/qcm/$quizId'
    | '/lecons/'
    | '/materiel/'
    | '/qcm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AproposRoute: typeof AproposRoute
  LeconsLessonIdRoute: typeof LeconsLessonIdRoute
  MaterielMaterielIdRoute: typeof MaterielMaterielIdRoute
  MaterielJeuRoute: typeof MaterielJeuRoute
  QcmQuizIdRoute: typeof QcmQuizIdRoute
  LeconsIndexRoute: typeof LeconsIndexRoute
  MaterielIndexRoute: typeof MaterielIndexRoute
  QcmIndexRoute: typeof QcmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apropos': {
      id: '/apropos'
      path: '/apropos'
      fullPath: '/apropos'
      preLoaderRoute: typeof AproposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons/': {
      id: '/lecons/'
      path: '/lecons'
      fullPath: '/lecons/'
      preLoaderRoute: typeof LeconsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons/$lessonId': {
      id: '/lecons/$lessonId'
      path: '/lecons/$lessonId'
      fullPath: '/lecons/$lessonId'
      preLoaderRoute: typeof LeconsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiel/': {
      id: '/materiel/'
      path: '/materiel'
      fullPath: '/materiel/'
      preLoaderRoute: typeof MaterielIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiel/$materielId': {
      id: '/materiel/$materielId'
      path: '/materiel/$materielId'
      fullPath: '/materiel/$materielId'
      preLoaderRoute: typeof MaterielMaterielIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiel/jeu': {
      id: '/materiel/jeu'
      path: '/materiel/jeu'
      fullPath: '/materiel/jeu'
      preLoaderRoute: typeof MaterielJeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qcm/': {
      id: '/qcm/'
      path: '/qcm'
      fullPath: '/qcm/'
      preLoaderRoute: typeof QcmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qcm/$quizId': {
      id: '/qcm/$quizId'
      path: '/qcm/$quizId'
      fullPath: '/qcm/$quizId'
      preLoaderRoute: typeof QcmQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AproposRoute: AproposRoute,
  LeconsLessonIdRoute: LeconsLessonIdRoute,
  MaterielMaterielIdRoute: MaterielMaterielIdRoute,
  MaterielJeuRoute: MaterielJeuRoute,
  QcmQuizIdRoute: QcmQuizIdRoute,
  LeconsIndexRoute: LeconsIndexRoute,
  MaterielIndexRoute: MaterielIndexRoute,
  QcmIndexRoute: QcmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
